### PR TITLE
Added documentation & char highlighting

### PR DESCRIPTION
**Pull request by IamMaxim**
Documentation uses default documentation colors and looks like this:

image

Also fixed characters highlighting, before this, the IDE wasn't recognizing them and marked as syntax errors.

### CODE REVIEW

**Comment by pirocks** [comment]
> Also fixed characters highlighting

Thanks I was aware of that problem, but hadn't gotten around to fixing it.

**Comment by SingingBush** [comment]
thanks for the PR. I had a quick look and it seems fine to merge but I've not got time to test properly at the moment.
@pirocks are you happy with this being merged? My only real concern is the regenerating of _DLanguageHighlightingLexer_ I seem to recall @kingsleyh mentioning that some generated code also had manual edits.

**Comment by kingsleyh** [comment]
We should get rid of the separate lexer for highlighting and use the main one - it was an experiment that failed but I never got round to backing out

**Comment by pirocks** [comment]
> We should get rid of the separate lexer for highlighting and use the main one - it was an experiment that failed but I never got round to backing out

I disagree.  Specifically having a separate highlighting and parsing lexer, allows us to support syntax highlighting in token strings, while still parsing them correctly, and it allows us to correctly parse the `import std.string` and have highlighting for the `string` keyword.

**Comment by kingsleyh** [comment]
Well since you are doing the work I'll leave it up to you - but managing 2 lexers which are almost identical seems like a pain esp when updating them.

**Pull request merged**
