### PR TITLE
Added unions to structure view and updated node icons

### PR DESCRIPTION
**Pull request by sysint64**

### CODE REVIEW

**Comment by pirocks** [comment]
image

Unions still don't seem to be showing up in the structure view. Is this intended behavior?

**Comment by sysint64** [comment]
@pirocks are you sure that it's new build? in my IDEA it looks like this:
[screnshot](https://i.imgur.com/ONoYsfr.png)

**Comment by pirocks** [comment]
That's odd. I'll investigate

**Comment by sysint64** [comment]
@pirocks in your IDEA icon for property (getter) also old

**Comment by pirocks** [comment]
Ok then I probably didn't git pull.

**Pull request merged**
