### PR TITLE
Redo the resolve algorithms

### LINKED ISSUE #595: IllegalArgumentException in DNameScopeProcessor
**Desktop (please provide environment info):**
 - OS: Windows 10
 - IDE: Intellij 2020.1
 - Plugin Version: 1.24.2

```
java.lang.IllegalArgumentException: null
    at io.github.intellij.dlanguage.attributes.DNameScopeProcessor.handleImport(DNameScopeProcessor.kt:62)
    at io.github.intellij.dlanguage.attributes.DNameScopeProcessor.execute(DNameScopeProcessor.kt:41)
    at io.github.intellij.dlanguage.resolve.ScopeProcessorImplUtil.processDeclaration(ScopeProcessorImplUtil.kt:77)
    at io.github.intellij.dlanguage.psi.DlangFile.processDeclarations(DlangFile.java:105)
    at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1150)
    at io.github.intellij.dlanguage.resolve.processors.basic.BasicResolve.findDefinitionNode(BasicResolve.kt:42)
    at io.github.intellij.dlanguage.annotator.DHighlightingAnnotator.highlightReference(DHighlightingAnnotator.kt:31)
    at io.github.intellij.dlanguage.annotator.DHighlightingAnnotator.annotate(DHighlightingAnnotator.kt:14)
    at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:129)
    at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:110)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:346)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:280)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:306)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:309)
    at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:309)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:277)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:222)
    at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:52)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:434)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:427)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:402)
    at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:168)
    at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:168)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:400)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:171)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

### LINKED ISSUE #865: Importing causes possibly undefined symbol on sub element
First I would like to kudos the team, my previous ticket  #846 was fixed and i even downloaded the new version and double checked is now working properly. That encourages me a lot to report other problems in the indexing area and hope this plugin becomes even better.

**Desktop (please provide environment info):**
 - OS: MacOs Ventura 13.2.1 (M1 pro apple chip)
 - IDE: IntelliJ IDEA 2023.1.1 (Community Edition)
 - Plugin Version 1.30.1

**D compiler and tools (please provide version numbers):**
 - dmd: DMD64 D Compiler v2.102.1
 - dub: DUB version 1.31.1, built on Feb 15 2023 (installed with brew)
 - dcd: v0.15.2
 - dscanner: v0.14.0

**Describe the problem**
I'm getting a "Possibly undefined symbol" warning when using importing a struct from a different module and accessing a substruct. This is even if the project compiles and go to definition for the external struct works properly.

**Please provide full details to reproduce the problem**
Add a file main.d:
```
module main;
import std.stdio;
import mylib: A;

void main() {
    A.B var;
    writeln("Finished.");
}
```

Then a second file mylib.d:

```
module mylib;
struct A {
    struct B {

    }
}
```

Screenshot 2023-05-11 at 14 24 15

### LINKED ISSUE #924: IllegalArgumentException when handling imports
plugin version 1.32.4
Intellij 2023.3.4

```
java.lang.IllegalArgumentException: null
    at io.github.intellij.dlanguage.attributes.DNameScopeProcessor.handleImport(DNameScopeProcessor.kt:68)
    at io.github.intellij.dlanguage.attributes.DNameScopeProcessor.execute(DNameScopeProcessor.kt:49)
    at io.github.intellij.dlanguage.resolve.ScopeProcessorImplUtil.processDeclaration(ScopeProcessorImplUtil.kt:83)
    at io.github.intellij.dlanguage.psi.DlangFile.processDeclarations(DlangFile.java:120)
    at com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1250)
    at io.github.intellij.dlanguage.resolve.processors.basic.BasicResolve.findDefinitionNode(BasicResolve.kt:41)
    at io.github.intellij.dlanguage.annotator.DHighlightingAnnotator.highlightReference(DHighlightingAnnotator.kt:44)
    at io.github.intellij.dlanguage.annotator.DHighlightingAnnotator.annotate(DHighlightingAnnotator.kt:26)
    at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:128)
    at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:106)
```

### PR DESCRIPTION
**Pull request by etienne02**
This PR greatly improves the state of the resolution by re-implementing it (almost) completely. It now properly handle fully qualified name for Type references (nested element access) and is more clear to understand.
It is greatly inspired by the implementation from Jetbrains for Java language.
There is no performance optimization for now and some structure/pattern could be bring to improve the global re-usability of code.

There is still a lot more to do, like checking for accessibility (private or protected access checks), checking for the good overload used, field access of a class or a struct, …, but they require a more complete comprehension of the elements (Adding Type handling, method signature for selecting the good overload, …) that will be added later as otherwise the PR will be too big.
There is also a lot more case to cover with tests.

Some regressions are expected (especially with imports where some tests were disabled for now) until the next PRs that will add the necessary elements to have a correct resolve.

Also the native completion support was removed for now until a proper and full implementation will be re-added. The feature is probably not currently used because it’s so wrong (always add all the known symbols without taking care of context).

Close #865
Close #924 
Close #595

### CODE REVIEW

**Review by SingingBush — COMMENTED** [review]
I've not had time to check it out and run locally but all looks good. Just message me when you're finished and ready to get it merged.

**Comment by rikkimax** [comment]
I hope this means that we won't need DCD for auto-completion, and we can disable DScanner's symbol not found error!

Will be looking forward to trying it out.

**Comment by etienne02** [comment]
> I hope this means that we won't need DCD for auto-completion, and we can disable DScanner's symbol not found error!
> 
> Will be looking forward to trying it out.

Exactly, this currently needs some work but that’s the final goal. No need of external tool for completion and analysis.
I will try to bring them as fast as possible.

**Comment by SingingBush** [comment]
This worked pretty well when testing locally. There was an issue when opening an existing dub project but I believe that's unrelated. Let's hold off on releasing for a while so we can dogfood the changes and fix any issues.

**Pull request merged**
