### PR TITLE
Add support for SDLang

### PR DESCRIPTION
**Pull request by etienne02**
This adds syntax support of Simple Definition Language, with basic editors fonctionalities.
image

### CODE REVIEW

**Comment by SingingBush** [comment]
This is awesome. I'm happy to merge but have you considered releasing as a standalone plugin? SDLang isn't uniquely tied to dub or the D community (in fact when I spoke to [the author](https://github.com/dleuck) he wasn't aware of it's use in the D community at all) so it could have value as a plugin in its own right.

I'll wait for confirmation before merging

**Comment by etienne02** [comment]
Ok, I’ll designed the plugin to be able to move it into an independent plugin easily

**Comment by SingingBush** [comment]
I guess I should've merged this before the json schema PR. As posted on other thread, I'll merge it as-is for now. If you want to release a standalone sdl plugin at some point then it's easy enough to unpick

**Comment by etienne02** [comment]
Conflict resolved

**Pull request merged**
