### PR TITLE
Make the DCD completions async

### PR DESCRIPTION
**Pull request by madmax-inc**
Relates: #328, #455

### CODE REVIEW

**Comment by SingingBush** [comment]
Could you rebase this and force push

**Comment by madmax-inc** [comment]
> Could you rebase this and force push

Oh, sure ) I've just wanted to review this first and write some tests before making it public ) Thanks.

**Comment by SingingBush** [comment]
no problem, now that 2019.2 is the min SDK it may affect the changes. Also, need to ensure that the travis build passes. That will only be possible if rebased

**Comment by andre2007** [comment]
@madmax-inc thanks for the pull request. As you referenced the UI freeze issue. My gut feeling is, there are 3 issues causing UI freeze, this is 1 of them.
The other two are:
- calling dub (dmd) on every few key press for syntax check
- internal Intellij/d-plugin formatter called on every few key press

Your pull request will improve the situation but maybe not solve the ui freeze issue. My idea is two add 2 new check boxes to the plugin settings to disable dub syntax checks / internal formatted while writing code.

**Comment by SingingBush** [comment]
@madmax-inc I'd still like to get this in. Could you rebase with the current develop branch

**Comment by madmax-inc** [comment]
> @madmax-inc I'd still like to get this in. Could you rebase with the current develop branch

Done. I checked out on vibe-d sources and seems @andre2007 was right: this is only the beginning. =(
Moreover one day it was throwing an exception "Synchronous execution on EDT". Unfortunately I didn't save a stacktrace but what I saw is that it is related to `which dub`, `dub ...`, `dmd ...`. Maybe we should make all the calls asynchronous in a single PR? What do you think, @SingingBush, @andre2007  ?

**Comment by SingingBush** [comment]
I did some work on some of them over the weekend. Best to do smaller bits of work so treat D Tool as separate issue

**Comment by SingingBush** [comment]
Seems that my change to `ExecUtil.readCommandLine()` has caused this to need rebasing again

**Comment by rikkimax** [comment]
Ping?

**Pull request merged**
