### PR TITLE
Rearchitecture switch to multi module

### PR DESCRIPTION
**Pull request by etienne02**
Based on https://github.com/intellij-dlanguage/intellij-dlanguage/pull/926

The split to api + impl is not perfect (some are still in api while should be in impl), but this works and some can be completed later.

A lot of files affected but it’s just a move for most of them, no content change.

### CODE REVIEW

**Comment by SingingBush** [comment]
a refactor of this size will cause significant problems for some ongoing changes in feature branches. If it absolutely needs doing then we should consider how it can be broken down into smaller changes that can be done in stages

**Comment by etienne02** [comment]
> a refactor of this size will cause significant problems for some ongoing changes in feature branches. If it absolutely needs doing then we should consider how it can be broken down into smaller changes that can be done in stages

I tried to move only the minimal to APl, but the there is too much interdependency between all classes. Just extracting the class required by Dub module bring me to the current API stuff you have.

To do it incrementally, I can create a dlang/dlang-impl module with only the plugin.xml file (something like intellij-rust plugin did). This would break the circular dependency and solve our immediate problem. Then we can incrementally move files into a proper architecture with more modules.
In the long term, I would like to have a more modular architecture. I have in mind something similar to intellij-community or intellij-scala.

What do you think about it?

**Comment by SingingBush** [comment]
> What do you think about it?

That seems a lot more reasonable for now. I am in favour of separation. That's the direction it's been heading for a while but it's a long running evolution. Would you be interested in discussing over slack this evening? I can be online in around an hour and be available for a few hours.

**Comment by etienne02** [comment]
> > What do you think about it?
> 
> That seems a lot more reasonable for now. I am in favour of separation. That's the direction it's been heading for a while but it's a long running evolution. Would you be interested in discussing over slack this evening? I can be online in around an hour and be available for a few hours.

yes

**Pull request closed without merging**
