### PR TITLE
#57 further CLion support: opening existing projects, auto detect dmd compiler, APIs cleanup

### PR DESCRIPTION
**Pull request by amakeev**
* basic ProjectOpenProcessor to open dub-based projects in CLion
* extract IDEA-only plugin dependencies
* replace usages of IDEA-only APIs with generic APIs
* auto-detect dmd compiler from MacPorts

More details are provided in the inline comments

### CODE REVIEW

**Comment by SingingBush** [comment]
thanks for this. Will these changes mean that we should target 2018.1 as the min supported?

**Comment by amakeev** [comment]
@SingingBush Though, there is no 2018.1-specific API usages in the plugin; non-CMake projects and custom New Project wizard are only available in CLion 2018.1+. So indeed, CLion-specific functionality only makes sense since 2018.1.
But the plugin should be fully compatible with earlier versions of IntelliJ IDEA.

There are two options: 
- bump the min platform version to 181 and publish a single plugin
- if you want to have a backward-compatible plugin, publish 2 separate plugins, one for IntelliJ IDEA (and keep current min version) and another one for CLion (with min 181).

In case CLion-specific API will be used in future (e.g. built-in native debugger support), the min version should be set to the most recent/tests CLion version (since CLion API is much less stable than IDEA's)

**Comment by SingingBush** [comment]
Have kicked off a release for v1.16.2 and set target Intellij version as 2018.1 - will get this out in the v1.17 release. Hopefully in time for dconf

**Comment by amakeev** [comment]
@SingingBush Cool, thanks! There is a hackathon planned after the DConf Munich, couple of guys wanted to work on the further integration with CLion, I'll let them know that the PR is in upstream.
Are you coming to the DConf?

**Comment by SingingBush** [comment]
unfortunately not, I had considered it (partly as I have friends in Munich that I could visit at the same time). I'll send you an invite to [our intellij-dlang.slack.com](https://intellij-dlang.slack.com) in case you want to ask any questions during the hackathon.

**Comment by amakeev** [comment]
@SingingBush Thanks for the offer! I'm not participating either, but I'll pass to the other guys.

**Pull request merged**
