### PR TITLE
Enable MagoMI / GDB on Windows Subsystem for linux 

### PR DESCRIPTION
**Pull request by andre2007**
This pull requests enables MagoMI as GDB replacement on windows and also debugging linux applications on Windows using Windows Subsystem for linux.

### GDB WSL
Debugging is possible, variables are shown and stack trace is also working now. 
For testing create a batch file "dubwsl.bat" with content:
```
@ECHO OFF
wsl dub %*
```

and a batch file "gdbwsl.bat" with content:
```
@ECHO OFF
wsl gdb %*
```
Set dubwsl.bat as dub file path and gdbwsl.bat as gdb file path.

image

image

### MagoMI

-var-update command bug is fixed and debugging is also possible now. But there are some issues with the stack trace:
- Variable content seems to be wrong
- app.d is mentioned 2 times (https://github.com/rainers/mago/issues/21) -> DMD bug?

image

Find newest mago-mi here
https://ci.appveyor.com/project/rainers/mago

### Additional notes

This pr also introduce the dub package fields targetPath and targetFileName. Unfortunately ```dub describe``` does not encode "/" with a "\\". This causes an Java/Kotlin JSON exception if a / is in field targetPath like "bin/". Dub describe should output "bin\\/".
There is an open issue on dub https://github.com/dlang/dub/issues/1494

### CODE REVIEW

**Comment by SingingBush** [comment]
These changes look fine and the builds are passing. The gdb code was added by @pirocks so I'd prefer if they give green light before merging this.

**Comment by andre2007** [comment]
For the moment please wait before merging. I will remove the WIP flag from the title when the pr is in a good shape. I already opened the pr to give other developers the chance to help here. Before merging maybe a test on Linux makes sense to check whether this pr doesn't introduce bugs here.

**Comment by andre2007** [comment]
There are strange TravisCI errors like:

JavaNCSS got an error while parsing the java file /home/travis/build/intellij-dlanguage/intellij-dlanguage/src/main/java/io/github/intellij/dlanguage/DlangSdkType.java
ParseException in STDIN
Last useful checkpoint: "io.github.intellij.dlanguage.DlangSdkType.setupSDKPathsFromWindowsConfigFile(Sdk,SdkModificator)"
Encountered " ">" "> "" at line 345, column 54.

These file weren't touched within this pr. Is this a known issue?

**Comment by pirocks** [comment]
>These file weren't touched within this pr. Is this a known issue?

I've seen similar errors before, however I believe restarting the build should fix them. I'm not to sure of the cause.

**Comment by andre2007** [comment]
Green

**Comment by SingingBush** [comment]
I did a rebase/merge for #433 so this branch may need rebasing. Also it's probably a good idea to use some of the comments/screenshots in this PR for documenting how to use configure debugging.

Do these changes break debugging on Linux or Mac?

**Comment by andre2007** [comment]
I validated debugging on linux using the Windows Sub System for Linux. Unfortunately I do not own an Mac. But it would be a good idea to retest it own MacOS.

As far as I see Github is fine without rebasing (This branch has no conflicts with the base branch).
Yes it makes really sense to enhance the README. I would do this as separate pr.

**Comment by andre2007** [comment]
Thanks  a lot. Today I tried the new WSL functionality on another windows system. There the plugin hangs on ExecUtil.java within method readCommandLine. This method is called e.g. on setting dub /gdb path.
This bug is located in Windows (WSL) itself and is already solved with an recent windows system. More information on the bug here (https://github.com/Microsoft/WSL/issues/2592). I will include this info when enhancing the documentation.

**Pull request merged**
