### PR TITLE
Adds error reporting submitter

### PR DESCRIPTION
**Pull request by pirocks**
Exceptions are reported to https://github.com/Auto-Generated-Error-Reporter/DIntellijPluginAutoGeneratedIssues/issues. This can be configured to the main repository, but it would probably be best to keep error reporting from the IDE separate from manual reporting. 
Most of the code was adapted from:
https://github.com/halirutan/Mathematica-IntelliJ-Plugin/tree/5d275b7a8ea528d9fa8f6681dc001bffb9bc15a3/src/de/halirutan/mathematica/errorreporting. This means that we have to distribute the copyright from @halirutan with the plugin. I added it to the readme, and it should probably go in the release notes for the next release.

### CODE REVIEW

**Comment by pirocks** [comment]
The coverage seems wrong. I didn't unittest the error submitter so I would have expected coverage to go down. Also if you click through to the coverage details it only lists 46 files, however we definitely have more than 46 source files.

**Comment by SingingBush** [comment]
coveralls should show correct information now
https://github.com/intellij-dlanguage/intellij-dlanguage/commit/0df5171364bc31eedff59109d1c5235d59c0e2ff

The _errorHandler_ needs to wait for a bit so I'm holding off on merging this. I don't want to use halirutan's code directly as don't want to post bug reports directly into github (and wouldn't have access token in the build) but am happy to use it as reference along with what Google do for Android Studio.  

The server-side stuff I have planned will be more useful and we can have that post into either github or slack if needs be

**Comment by halirutan** [comment]
@SingingBush Just for your information let me give some details. I wrote the code on the basis of several existing error-reporters where the Android Studio was a major influence. Instead of dealing with the GitHub servers manually, I used the `org.eclipse.egit.github.core` library which has proven its reliability in many projects.
Opposed to the code in Android Studio, I have written a lot of comments and which I hope helped @pirocks to adapt the sources. One of the major advantages compared to the implementation in Android Studio is that I built in a check for *duplicate issues* which happen *a lot* when you reach a certain number of users. All similar exceptions are collected in the same issue by using GitHub comments. The downside to this is that you need to have write-access because commenting is not allowed for anonymous users.

There is at the moment no secure way to achieve GitHub write access for a plugin. One would need a server that provides the GitHub access token for your plugin. Such a "sensitive data provider" for plugins should be provided by Jetbrains in the same way it is provided by e.g. TravisCI. At the moment, I'm providing a way to encrypt and decrypt access tokens, but even if you don't store the encrypted GitHub token in your code, but inject it later, someone can decompile your plugin and inspect it. I have written in detail about all this here

- [Community Post: Automatic error reporting to GitHub issues](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000406190-Answer-Automatic-error-reporting-to-GitHub-issues)
- [package-info.java](https://github.com/halirutan/Mathematica-IntelliJ-Plugin/blob/5d275b7a8ea528d9fa8f6681dc001bffb9bc15a3/src/de/halirutan/mathematica/errorreporting/package-info.java)

**Comment by pirocks** [comment]
>One of the major advantages compared to the implementation in Android Studio is that I built in a check for duplicate issues which happen a lot when you reach a certain number of users. 

I commented this out because we don't have that many users afaik. The autoreporting repository and autoreporting user is separate from the main repository.

**Comment by SingingBush** [comment]
@halirutan thanks for the the extra info. My hesitation is because I've been planning to put together a little webapp that the plugin can post error reports and some basic usage info to. The webapp can aggregate the info and would be responsible for posting bug reports to github or slack. So any tokens would be kept on the server.

**Pull request closed without merging**
